# Generated by Django 3.0.8 on 2020-08-08 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=10)),
                ('category', models.CharField(max_length=20)),
                ('img', models.CharField(blank=True, default='', max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('sold_on', models.DateField(default='null', null=True)),
                ('is_active', models.BooleanField()),
                ('sold_to', models.CharField(blank=True, max_length=150)),
                ('sold_for', models.FloatField(blank=True, max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watch_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(max_length=10)),
                ('al_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction_listing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=250)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('al_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction_listing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField(max_length=10)),
                ('al_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Auction_listing')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
