# Generated by Django 3.0.8 on 2020-08-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200808_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='sold_for',
            field=models.FloatField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='sold_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
