# Generated by Django 3.0.8 on 2020-08-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200808_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch_list',
            name='bid',
        ),
    ]
