# Generated by Django 3.0.8 on 2020-08-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20200810_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='img',
            field=models.ImageField(blank=True, default='default_img.png', null=True, upload_to=''),
        ),
    ]
