# Generated by Django 3.0.8 on 2020-08-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200810_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_title',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
