# Generated by Django 3.0.8 on 2020-08-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_comments_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
