# Generated by Django 3.0.8 on 2020-08-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200814_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='sold_for',
            new_name='maxBid',
        ),
    ]
