# Generated by Django 3.0.8 on 2020-08-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20200816_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='maxBid',
            new_name='max_bid',
        ),
    ]
