# Generated by Django 3.0.8 on 2020-08-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200816_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='bidders_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='watchers_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
