# Generated by Django 3.0.8 on 2020-08-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20200818_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='created_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
