# Generated by Django 3.0.8 on 2020-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20200819_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
