# Generated by Django 3.0.8 on 2020-08-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20200820_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='sold_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
