# Generated by Django 3.0.8 on 2020-08-20 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20200820_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='sold_to',
            new_name='sold_toUser',
        ),
    ]
