# Generated by Django 3.0.8 on 2020-08-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20200820_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='sold_to',
        ),
    ]
