# Generated by Django 3.0.8 on 2020-08-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_remove_auction_listing_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='sold_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
