# Generated by Django 3.0.8 on 2020-08-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auction_listing_sold_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
