# Generated by Django 3.0.8 on 2020-08-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0035_auto_20200820_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='bids_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
